[package]
name = "sasm"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smpl_core_common = { git = "https://github.com/SmplWorks/SmplCore-common.git", branch = "main" }
thiserror = "1.0.56"
